name: biol5472_groupB
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.12
  - jinja2>=3.1
  - pandas>=2.0
  - numpy>=1.26
  - matplotlib>=3.8
  - seaborn>=0.13
  - biopython>=1.85
  - snakemake>=9
  - pip

  - pip:
      - gffutils>=0.12
