name: biol5472_groupB
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - pandas=2.*
  - pip=24.*
  - snakemake=9.*
  - numpy=1.*
  - matplotlib=3.*
  - seaborn=0.*
  - gffutils=0.*
  - biopython=1.*
